### ISSUE TITLE
Building without Python support fails

### ISSUE THREAD

**Issue by pscff** [SINTEF/dlite#146]
One of the tests expects a reference which seems to be generated only with -DWITH_PYTHON=ON

```
$ mkdir out/build/noPython
$ cd out/build/noPython
$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING="Release" -DWITH_DOC=OFF -DWITH_HDF5=OFF -DWITH_PYTHON=OFF -DALLOW_WARNINGS=ON ../../.. 
$ cmake --build . --config Release
...
[ 74%] Linking C executable test_mapping
/usr/bin/ld: ../libdlite.so: undefined reference to `dlite_python_mapping_next'
/usr/bin/ld: ../libdlite.so: undefined reference to `dlite_python_mapping_paths_get'
collect2: error: ld returned 1 exit status
make[2]: *** [src/tests/CMakeFiles/test_mapping.dir/build.make:86: src/tests/test_mapping] Error 1
make[1]: *** [CMakeFiles/Makefile2:1994: src/tests/CMakeFiles/test_mapping.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

Obvious workaround

- Compile with Python support
- One (or more?) tests must be excluded when setting -DWITH_PYTHON=OFF

**Comment by jesper-friis** [comment]
Hi @pscff, I guess this issue is fixed and can be closed?

**Comment by pscff** [comment]
The issue is still present for the current master, the build fails already in the cmake-configure step now. How to reproduce: Set `-DWITH_PYTHON=OFF` in your build-system and try to build.
